language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
after_success:
  - ' echo $TRAVIS_BRANCH'
  - ' echo $TRAVIS_PULL_REQUEST'
  - 'if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false"]; then npm run semantic-release fi'
  - 'if [ "$TRAVIS_BRANCH" == "development" ]; then exit 0; fi'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
